import Head from "next/head";
import Link from "next/link";
import Hero from "~/components/Hero";
export default function Home() {
  return (
    <>
      <Head>
        <title>FocusFoods</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full max-h-max font-bebas">
        <Hero></Hero>
        <section className = "w-full min-h-screen" >

        </section>
      </main>
    </>
  );
}
